### ISSUE TITLE
Admin > Service provider > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [rajasrivastava101/Valchlinks-Tracker#24]
![image](https://github.com/rajasrivastava101/Valchlinks-Tracker/assets/129847373/0dd45707-86d2-451b-9e17-9058fa623fea)
In adding a new location, the dropdown does not show suggestions nor a user can add it.

**Comment by guptaAman271298** [comment]
Give hint from where he/she can add new city

**Comment by rajasrivastava101** [comment]
![image](https://github.com/rajasrivastava101/Valchlinks-Tracker/assets/129847373/b01e4b1b-405e-4bff-aad1-4d045f47d2c5)
Not able to add new city.
