### ISSUE TITLE
Admin > Master settings > add user > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [rajasrivastava101/Valchlinks-Tracker#41]
![image](https://github.com/rajasrivastava101/Valchlinks-Tracker/assets/129847373/d569f954-3a43-45b0-9427-201cd090a80b)
Client industry type is accepting the digits. should not accept.

**Comment by rajasrivastava101** [comment]
Still accepting digits on both ends , on add user page as well as on detail page in advance filter option.

**Comment by utsav-vayuz** [comment]
Modified this field to not accept numbers and special character but also to show error to user
