### ISSUE TITLE
Admin > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [rajasrivastava101/Valchlinks-Tracker#52]
Kindly add CMS for privacy policy , platform declaration.

**Comment by rajasrivastava101** [comment]
In CMS there will be a page for Cookies settings, about the website and privacy policy. I will share the reference for the same.

**Comment by guptaAman271298** [comment]
I have done it like if admin want to add any new static page content, edit the existing page content, activate or deactivate the existing page content. Now admin page the Privacy policy, platform declaration or any type of static page.
